version: '3'
services:
  reverse-proxy:
   image: traefik:v2.3 
   # Enables the web UI and tells Traefik to listen to docker
   command: --api.insecure=true --providers.docker
   ports:
   - 80:80
   depends_on:
   - app 

  app:
    image: kostua/petclinic:latest 
    expose:
      - "8080"
